#pragma once
const int SUCCESS_ERROR = 0;
const int WRONG_GENOME_SIZE_ERROR = -1;
const int WRONG_KNAPSACK_SIZE_ERROR = -2;
const int WRONG_NUMBER_OF_ITEMS_ERROR = -3;
const int WRONG_ITEMS_FORMAT_ERROR = -4;
const int FILE_NOT_OPEN_ERROR = -5;
const int WRONG_INDEX_FORMAT_ERROR = -6;
const int WRONG_ITEM_SIZE_ERROR = -7;
const int WRONG_ITEM_VALUE_ERROR = -8;
const int WRONG_POPULATION_SIZE_ERROR = -9;
const int WRONG_ITERATION_TIME_ERROR = -10;
const int WRONG_CROSSOVER_PROBABILITY_ERROR = -11;
const int WRONG_MUTATION_PROBABILITY_ERROR = -12;
const int EMPTY_VECTOR_ERROR = -13;
const int WRONG_ARGUMENT_TYPE_IN_FILE_ERROR = -14;